"""
Factor System Database Models for OpenFi Lite.

This module defines SQLAlchemy ORM models for the factor analysis and quantitative backtesting system,
including factors, factor values, backtest results, factor combinations, screening presets, and LLM analysis logs.
"""

from datetime import datetime
import uuid

from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from system_core.database.models import Base

class Factor(Base):
    """
    Factor definition model.
    
    Stores user-defined factor code, metadata, and configuration.
    Each factor represents a quantitative indicator used to predict asset price movements.
    """
    
    __tablename__ = "factors"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    factor_name = Column(String(100), nullable=False, unique=True, index=True)
    factor_code = Column(Text, nullable=False)
    description = Column(Text)
    category = Column(String(50), index=True)  # 'technical', 'fundamental', 'sentiment', 'alternative'
    
    # Data dependencies: which data sources this factor requires
    # Example: ["market_data", "news_data", "fundamental_data"]
    data_dependencies = Column(JSONB)
    
    # Factor parameters definition
    # Example: {"lookback_period": {"type": "int", "default": 20, "min": 1, "max": 252}}
    parameters = Column(JSONB)
    
    version = Column(Integer, nullable=False, default=1)
    is_active = Column(Boolean, nullable=False, default=True, index=True)
    
    created_by = Column(UUID(as_uuid=True), ForeignKey("users.id"))
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False
    )
    
    # Relationships
    factor_values = relationship("FactorValue", back_populates="factor", cascade="all, delete-orphan")
    creator = relationship("User", backref="factors")
    
    def __repr__(self):
        return f"<Factor(id={self.id}, factor_name={self.factor_name}, category={self.category})>"

class FactorValue(Base):
    """
    Factor value model.
    
    Stores calculated factor values for specific symbols and dates.
    This is the time-series data generated by factor calculations.
    """
    
    __tablename__ = "factor_values"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    factor_id = Column(UUID(as_uuid=True), ForeignKey("factors.id", ondelete="CASCADE"), nullable=False)
    symbol = Column(String(20), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    value = Column(Numeric(20, 8))
    
    # Additional metadata: calculation time, data quality, etc.
    # Example: {"calculation_time_ms": 123, "data_quality": "good", "missing_data_points": 0}
    calc_metadata = Column(JSONB)  # Renamed from 'metadata' to avoid SQLAlchemy reserved word
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    
    # Relationships
    factor = relationship("Factor", back_populates="factor_values")
    
    # Composite index for efficient queries
    __table_args__ = (
        # Index on (factor_id, symbol, date) for fast lookups
    )
    
    def __repr__(self):
        return f"<FactorValue(factor_id={self.factor_id}, symbol={self.symbol}, date={self.date}, value={self.value})>"

class BacktestResult(Base):
    """
    Backtest result model.
    
    Stores complete backtest results including performance metrics, equity curve, and trade details.
    Supports EA strategies, factor strategies, and combined strategies.
    """
    
    __tablename__ = "backtest_results"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    
    # Strategy type: 'ea', 'factor', or 'combined'
    strategy_type = Column(String(20), nullable=False, default='factor', index=True)
    strategy_name = Column(String(100), nullable=False)
    
    # EA-specific fields (optional, used when strategy_type='ea' or 'combined')
    ea_id = Column(String(100))
    
    # Factor-specific fields (optional, used when strategy_type='factor' or 'combined')
    # Array of factor IDs
    factor_ids = Column(JSONB)
    
    # Strategy configuration: parameters, entry/exit rules, weights
    # Example: {"factor_ids": ["uuid1", "uuid2"], "weights": [0.6, 0.4], "entry_threshold": 0.7}
    strategy_config = Column(JSONB, nullable=False)
    
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    initial_capital = Column(Numeric(20, 2), nullable=False)
    final_capital = Column(Numeric(20, 2))
    
    # Performance metrics
    total_return = Column(Numeric(10, 4))  # e.g., 0.4523 = 45.23%
    annual_return = Column(Numeric(10, 4))
    max_drawdown = Column(Numeric(10, 4))
    sharpe_ratio = Column(Numeric(10, 4))
    win_rate = Column(Numeric(5, 4))  # e.g., 0.58 = 58%
    profit_loss_ratio = Column(Numeric(10, 4))
    total_trades = Column(Integer)
    
    # Equity curve: time-series of portfolio value
    # Example: [{"date": "2023-01-01", "value": 100000}, {"date": "2023-01-02", "value": 100500}, ...]
    equity_curve = Column(JSONB)
    
    # Trade details: list of all simulated trades
    # Example: [{"entry_date": "2023-01-01", "exit_date": "2023-01-05", "symbol": "AAPL", "pnl": 500}, ...]
    trade_details = Column(JSONB)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    
    # Relationships
    user = relationship("User", backref="backtest_results")
    
    def __repr__(self):
        return f"<BacktestResult(id={self.id}, strategy_name={self.strategy_name}, total_return={self.total_return})>"

class FactorCombination(Base):
    """
    Factor combination model.
    
    Stores multi-factor combinations with optimized weights.
    Allows users to create composite strategies from multiple factors.
    """
    
    __tablename__ = "factor_combinations"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    combination_name = Column(String(100), nullable=False)
    
    # Factor weights: mapping of factor_id to weight
    # Example: {"uuid1": 0.6, "uuid2": 0.3, "uuid3": 0.1}
    factor_weights = Column(JSONB, nullable=False)
    
    optimization_method = Column(String(50))  # 'equal_weight', 'ic_weighted', 'max_sharpe'
    description = Column(Text)
    is_active = Column(Boolean, nullable=False, default=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False
    )
    
    # Relationships
    user = relationship("User", backref="factor_combinations")
    
    def __repr__(self):
        return f"<FactorCombination(id={self.id}, combination_name={self.combination_name}, user_id={self.user_id})>"

class ScreeningPreset(Base):
    """
    Screening preset model.
    
    Stores saved factor screening conditions for quick reuse.
    Users can save their favorite screening criteria as presets.
    """
    
    __tablename__ = "screening_presets"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    preset_name = Column(String(100), nullable=False)
    
    # Factor conditions: screening criteria
    # Example: [{"factor_id": "uuid1", "operator": ">", "threshold": 0.05}, ...]
    factor_conditions = Column(JSONB, nullable=False)
    
    # Additional filters: industry, market cap, etc.
    # Example: {"industries": ["Technology", "Finance"], "min_market_cap": 1000000000}
    additional_filters = Column(JSONB)
    
    description = Column(Text)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False
    )
    
    # Relationships
    user = relationship("User", backref="screening_presets")
    
    def __repr__(self):
        return f"<ScreeningPreset(id={self.id}, preset_name={self.preset_name}, user_id={self.user_id})>"

class FactorAnalysisLog(Base):
    """
    Factor analysis log model.
    
    Stores LLM-generated analysis of factor performance and backtest results.
    Provides AI-powered insights and recommendations.
    """
    
    __tablename__ = "factor_analysis_logs"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    factor_id = Column(UUID(as_uuid=True), ForeignKey("factors.id", ondelete="SET NULL"))
    backtest_id = Column(UUID(as_uuid=True), ForeignKey("backtest_results.id", ondelete="SET NULL"))
    
    analysis_type = Column(String(50), nullable=False)  # 'performance', 'combination', 'query'
    prompt = Column(Text, nullable=False)
    response = Column(Text, nullable=False)
    
    llm_provider = Column(String(50))  # 'openai', 'anthropic', etc.
    llm_model = Column(String(100))  # 'gpt-4', 'claude-3', etc.
    tokens_used = Column(Integer)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    
    # Relationships
    factor = relationship("Factor", backref="analysis_logs")
    backtest = relationship("BacktestResult", backref="analysis_logs")
    
    def __repr__(self):
        return f"<FactorAnalysisLog(id={self.id}, analysis_type={self.analysis_type}, llm_model={self.llm_model})>"
