"""
Core Backtest Engine for OpenFi Lite.

This module provides the core backtesting infrastructure shared by EA and factor strategies.
It implements event-driven simulation, position management, and performance metrics calculation.
"""

from dataclasses import dataclass, field
from datetime import datetime, date
from decimal import Decimal
from enum import Enum
from typing import Optional, Any
import pandas as pd
import numpy as np
from system_core.config import get_logger

logger = get_logger(__name__)

class LookaheadBiasError(Exception):
    """Exception raised when forward-looking bias is detected in backtest."""
    pass

class SignalType(Enum):
    """Trading signal types."""
    BUY = "buy"
    SELL = "sell"
    CLOSE = "close"

class OrderStatus(Enum):
    """Order execution status."""
    PENDING = "pending"
    FILLED = "filled"
    REJECTED = "rejected"
    CANCELLED = "cancelled"

@dataclass
class TradingSignal:
    """
    Trading signal generated by a strategy.
    
    Attributes:
        date: Signal generation date
        symbol: Trading symbol
        signal_type: Buy, sell, or close
        quantity: Number of shares/contracts
        price: Target price (optional, uses market price if None)
        metadata: Additional signal information
    """
    date: datetime
    symbol: str
    signal_type: SignalType
    quantity: float = 1.0
    price: Optional[float] = None
    metadata: dict[str, Any] = field(default_factory=dict)

@dataclass
class Trade:
    """
    Executed trade record.
    
    Attributes:
        trade_id: Unique trade identifier
        symbol: Trading symbol
        entry_date: Entry date
        entry_price: Entry price
        quantity: Position size
        exit_date: Exit date (None if still open)
        exit_price: Exit price (None if still open)
        pnl: Profit/loss (None if still open)
        commission: Total commission paid
        slippage: Total slippage cost
        metadata: Additional trade information
    """
    trade_id: str
    symbol: str
    entry_date: datetime
    entry_price: float
    quantity: float
    exit_date: Optional[datetime] = None
    exit_price: Optional[float] = None
    pnl: Optional[float] = None
    commission: float = 0.0
    slippage: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)
    
    def close_trade(self, exit_date: datetime, exit_price: float, commission: float = 0.0, slippage: float = 0.0):
        """Close the trade and calculate P&L."""
        self.exit_date = exit_date
        self.exit_price = exit_price
        self.commission += commission
        self.slippage += slippage
        
        # Calculate P&L
        gross_pnl = (exit_price - self.entry_price) * self.quantity
        self.pnl = gross_pnl - self.commission - self.slippage
    
    def is_open(self) -> bool:
        """Check if trade is still open."""
        return self.exit_date is None

@dataclass
class Position:
    """
    Current position in a symbol.
    
    Attributes:
        symbol: Trading symbol
        quantity: Position size (positive for long, negative for short)
        entry_price: Average entry price
        entry_date: Position entry date
        unrealized_pnl: Current unrealized P&L
    """
    symbol: str
    quantity: float
    entry_price: float
    entry_date: datetime
    unrealized_pnl: float = 0.0
    
    def update_unrealized_pnl(self, current_price: float):
        """Update unrealized P&L based on current price."""
        self.unrealized_pnl = (current_price - self.entry_price) * self.quantity

@dataclass
class Portfolio:
    """
    Portfolio state tracking.
    
    Attributes:
        cash: Available cash
        initial_capital: Starting capital
        positions: Current open positions
        equity_history: Time series of portfolio value
        trades: List of all trades
    """
    cash: float
    initial_capital: float
    positions: dict[str, Position] = field(default_factory=dict)
    equity_history: list[dict[str, Any]] = field(default_factory=list)
    trades: list[Trade] = field(default_factory=list)
    
    def get_total_value(self, current_prices: dict[str, float]) -> float:
        """Calculate total portfolio value."""
        positions_value = sum(
            pos.quantity * current_prices.get(pos.symbol, pos.entry_price)
            for pos in self.positions.values()
        )
        return self.cash + positions_value
    
    def update_positions_pnl(self, current_prices: dict[str, float]):
        """Update unrealized P&L for all positions."""
        for symbol, position in self.positions.items():
            if symbol in current_prices:
                position.update_unrealized_pnl(current_prices[symbol])

@dataclass
class BacktestConfig:
    """
    Backtest configuration parameters.
    
    Attributes:
        initial_capital: Starting capital
        commission_rate: Commission rate (e.g., 0.001 = 0.1%)
        slippage_rate: Slippage rate (e.g., 0.0005 = 0.05%)
        leverage: Maximum leverage allowed
        position_size_pct: Default position size as % of portfolio
        max_position_size: Maximum position size as % of portfolio
        risk_free_rate: Risk-free rate for Sharpe ratio calculation
        enable_lookahead_detection: Enable forward-looking bias detection
        strict_lookahead_check: Raise error on lookahead bias (vs warning)
    """
    initial_capital: float = 100000.0
    commission_rate: float = 0.001
    slippage_rate: float = 0.0005
    leverage: float = 1.0
    position_size_pct: float = 0.1
    max_position_size: float = 0.2
    risk_free_rate: float = 0.02
    enable_lookahead_detection: bool = True
    strict_lookahead_check: bool = False

@dataclass
class PerformanceMetrics:
    """
    Backtest performance metrics.
    
    Attributes:
        total_return: Total return (e.g., 0.45 = 45%)
        annual_return: Annualized return
        max_drawdown: Maximum drawdown
        sharpe_ratio: Sharpe ratio
        win_rate: Percentage of winning trades
        profit_loss_ratio: Average win / average loss
        total_trades: Total number of trades
        winning_trades: Number of winning trades
        losing_trades: Number of losing trades
        average_win: Average winning trade P&L
        average_loss: Average losing trade P&L
        max_consecutive_wins: Maximum consecutive winning trades
        max_consecutive_losses: Maximum consecutive losing trades
    """
    total_return: float = 0.0
    annual_return: float = 0.0
    max_drawdown: float = 0.0
    sharpe_ratio: float = 0.0
    win_rate: float = 0.0
    profit_loss_ratio: float = 0.0
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    average_win: float = 0.0
    average_loss: float = 0.0
    max_consecutive_wins: int = 0
    max_consecutive_losses: int = 0

@dataclass
class BacktestResult:
    """
    Complete backtest result.
    
    Attributes:
        strategy_name: Name of the strategy
        start_date: Backtest start date
        end_date: Backtest end date
        initial_capital: Starting capital
        final_capital: Ending capital
        metrics: Performance metrics
        equity_curve: Portfolio value over time
        trades: List of all trades
        positions: Final positions
        lookahead_violations: List of detected forward-looking bias violations
    """
    strategy_name: str
    start_date: datetime
    end_date: datetime
    initial_capital: float
    final_capital: float
    metrics: PerformanceMetrics
    equity_curve: pd.DataFrame
    trades: list[Trade]
    positions: dict[str, Position]
    lookahead_violations: list[dict[str, Any]] = field(default_factory=list)

class BacktestCore:
    """
    Core backtest engine with event-driven simulation.
    
    This class provides the fundamental backtesting infrastructure:
    - Trade execution simulation
    - Position management
    - Performance metrics calculation
    - Equity curve generation
    
    It is designed to be used by both EA and factor-based strategies.
    """
    
    def __init__(self, config: BacktestConfig):
        """
        Initialize backtest core.
        
        Args:
            config: Backtest configuration
        """
        self.config = config
        self.portfolio: Optional[Portfolio] = None
        self.trade_counter = 0
        self.lookahead_violations: list[dict[str, Any]] = []
        
        logger.info("backtest_core_initialized",
                   initial_capital=config.initial_capital,
                   commission_rate=config.commission_rate,
                   slippage_rate=config.slippage_rate,
                   lookahead_detection=config.enable_lookahead_detection)
    
    def detect_lookahead_bias(
        self,
        signals: list[TradingSignal],
        market_data: pd.DataFrame,
        factor_data: Optional[pd.DataFrame] = None
    ) -> list[dict[str, Any]]:
        """
        Detect forward-looking bias in signals and data.
        
        This method checks:
        1. Signal timestamps are not in the future relative to market data
        2. Factor data timestamps are not in the future relative to signal dates
        3. All data used for signal generation has timestamps <= signal date
        
        Args:
            signals: List of trading signals to validate
            market_data: Historical market data
            factor_data: Optional factor values data
            
        Returns:
            List of detected violations with details
        """
        violations = []
        
        if not self.config.enable_lookahead_detection:
            return violations
        
        logger.info("lookahead_detection_started",
                   num_signals=len(signals),
                   has_factor_data=factor_data is not None)
        
        # Prepare data
        market_data = market_data.copy()
        if 'date' in market_data.columns:
            market_data['date'] = pd.to_datetime(market_data['date'])
        
        # Get available market data dates per symbol
        market_dates_by_symbol = {}
        for symbol in market_data['symbol'].unique():
            symbol_data = market_data[market_data['symbol'] == symbol]
            market_dates_by_symbol[symbol] = set(symbol_data['date'].dt.date)
        
        # Check each signal
        for idx, signal in enumerate(signals):
            signal_date = signal.date.date() if isinstance(signal.date, datetime) else signal.date
            
            # Check 1: Signal has corresponding market data
            if signal.symbol in market_dates_by_symbol:
                available_dates = market_dates_by_symbol[signal.symbol]
                
                # Check if signal date has market data
                if signal_date not in available_dates:
                    # Check if signal is using future data
                    future_dates = [d for d in available_dates if d > signal_date]
                    if future_dates:
                        violation = {
                            'type': 'signal_future_data',
                            'signal_index': idx,
                            'signal_date': signal_date.isoformat(),
                            'symbol': signal.symbol,
                            'message': f"Signal at {signal_date} for {signal.symbol} but market data not available until later dates",
                            'earliest_future_date': min(future_dates).isoformat()
                        }
                        violations.append(violation)
                        logger.warning("lookahead_bias_detected",
                                     violation_type='signal_future_data',
                                     signal_date=signal_date.isoformat(),
                                     symbol=signal.symbol)
        
        # Check factor data if provided
        if factor_data is not None:
            factor_data = factor_data.copy()
            if 'date' in factor_data.columns:
                factor_data['date'] = pd.to_datetime(factor_data['date'])
            
            # Get factor dates per symbol
            factor_dates_by_symbol = {}
            for symbol in factor_data['symbol'].unique():
                symbol_data = factor_data[factor_data['symbol'] == symbol]
                factor_dates_by_symbol[symbol] = set(symbol_data['date'].dt.date)
            
            # Check each signal against factor data
            for idx, signal in enumerate(signals):
                signal_date = signal.date.date() if isinstance(signal.date, datetime) else signal.date
                
                if signal.symbol in factor_dates_by_symbol:
                    factor_dates = factor_dates_by_symbol[signal.symbol]
                    
                    # Check if any factor data is from the future
                    future_factor_dates = [d for d in factor_dates if d > signal_date]
                    
                    # If signal uses factor data, ensure no future data is used
                    # We check if there's factor data exactly on signal date
                    if signal_date in factor_dates:
                        # This is OK - using current or past data
                        pass
                    else:
                        # Check if signal might be using future factor data
                        if future_factor_dates:
                            # Find the closest future date
                            closest_future = min(future_factor_dates)
                            
                            # If the closest future date is very close, it might indicate lookahead
                            if (closest_future - signal_date).days <= 1:
                                violation = {
                                    'type': 'factor_future_data',
                                    'signal_index': idx,
                                    'signal_date': signal_date.isoformat(),
                                    'symbol': signal.symbol,
                                    'message': f"Signal at {signal_date} for {signal.symbol} may be using future factor data from {closest_future}",
                                    'future_factor_date': closest_future.isoformat()
                                }
                                violations.append(violation)
                                logger.warning("lookahead_bias_detected",
                                             violation_type='factor_future_data',
                                             signal_date=signal_date.isoformat(),
                                             symbol=signal.symbol,
                                             future_date=closest_future.isoformat())
        
        logger.info("lookahead_detection_completed",
                   total_violations=len(violations))
        
        return violations
    
    def validate_data_timestamps(
        self,
        current_date: datetime,
        data: pd.DataFrame,
        data_type: str = "market_data"
    ) -> bool:
        """
        Validate that all data timestamps are <= current simulation date.
        
        Args:
            current_date: Current simulation date
            data: DataFrame with date column
            data_type: Type of data being validated (for logging)
            
        Returns:
            True if all timestamps are valid, False otherwise
        """
        if not self.config.enable_lookahead_detection:
            return True
        
        if 'date' not in data.columns:
            logger.warning("data_missing_date_column",
                         data_type=data_type)
            return True
        
        # Convert to datetime
        data = data.copy()
        data['date'] = pd.to_datetime(data['date'])
        
        # Check for future dates
        current_date_normalized = pd.to_datetime(current_date).normalize()
        future_data = data[data['date'] > current_date_normalized]
        
        if len(future_data) > 0:
            violation = {
                'type': 'data_timestamp_violation',
                'current_date': current_date.isoformat(),
                'data_type': data_type,
                'num_future_rows': len(future_data),
                'future_dates': future_data['date'].unique().tolist()[:5],  # First 5
                'message': f"Found {len(future_data)} rows of {data_type} with timestamps after current date {current_date}"
            }
            self.lookahead_violations.append(violation)
            
            logger.warning("data_timestamp_violation",
                         current_date=current_date.isoformat(),
                         data_type=data_type,
                         num_future_rows=len(future_data))
            
            if self.config.strict_lookahead_check:
                raise LookaheadBiasError(
                    f"Forward-looking bias detected: {data_type} contains {len(future_data)} "
                    f"rows with timestamps after current simulation date {current_date}"
                )
            
            return False
        
        return True
    
    def simulate_trades(
        self,
        signals: list[TradingSignal],
        market_data: pd.DataFrame,
        start_date: datetime,
        end_date: datetime,
        factor_data: Optional[pd.DataFrame] = None
    ) -> BacktestResult:
        """
        Simulate trading based on signals and market data.
        
        Args:
            signals: List of trading signals
            market_data: Historical market data (columns: date, symbol, open, high, low, close, volume)
            start_date: Backtest start date
            end_date: Backtest end date
            factor_data: Optional factor values data for lookahead detection
            
        Returns:
            BacktestResult with complete simulation results
        """
        logger.info("backtest_simulation_started",
                   start_date=start_date.isoformat(),
                   end_date=end_date.isoformat(),
                   total_signals=len(signals))
        
        # Initialize lookahead violations list
        self.lookahead_violations = []
        
        # Detect forward-looking bias in signals
        if self.config.enable_lookahead_detection:
            violations = self.detect_lookahead_bias(signals, market_data, factor_data)
            if violations:
                logger.warning("lookahead_bias_violations_detected",
                             num_violations=len(violations))
                self.lookahead_violations.extend(violations)
                
                if self.config.strict_lookahead_check:
                    raise LookaheadBiasError(
                        f"Forward-looking bias detected: {len(violations)} violations found. "
                        f"First violation: {violations[0]['message']}"
                    )
        
        # Initialize portfolio
        self.portfolio = Portfolio(
            cash=self.config.initial_capital,
            initial_capital=self.config.initial_capital
        )
        
        # Sort signals by date
        signals_sorted = sorted(signals, key=lambda s: s.date)
        
        # Create signal index for fast lookup
        signals_by_date = {}
        for signal in signals_sorted:
            signal_date = signal.date.date() if isinstance(signal.date, datetime) else signal.date
            if signal_date not in signals_by_date:
                signals_by_date[signal_date] = []
            signals_by_date[signal_date].append(signal)
        
        # Prepare market data
        market_data = market_data.copy()
        if 'date' in market_data.columns:
            market_data['date'] = pd.to_datetime(market_data['date'])
        
        # Get unique trading dates
        trading_dates = sorted(market_data['date'].unique())
        trading_dates = [d for d in trading_dates if start_date <= d <= end_date]
        
        # Simulate each trading day
        for current_date in trading_dates:
            # Validate data timestamps if lookahead detection is enabled
            if self.config.enable_lookahead_detection:
                # Get data up to current date for validation
                historical_data = market_data[market_data['date'] <= current_date]
                self.validate_data_timestamps(current_date, historical_data, "market_data")
            
            # Get market data for current date
            current_data = market_data[market_data['date'] == current_date]
            current_prices = dict(zip(current_data['symbol'], current_data['close']))
            
            # Process signals for current date
            date_key = current_date.date() if isinstance(current_date, datetime) else current_date
            if date_key in signals_by_date:
                for signal in signals_by_date[date_key]:
                    self._execute_signal(signal, current_prices, current_date)
            
            # Update portfolio value
            self.portfolio.update_positions_pnl(current_prices)
            total_value = self.portfolio.get_total_value(current_prices)
            
            self.portfolio.equity_history.append({
                'date': current_date,
                'value': total_value,
                'cash': self.portfolio.cash,
                'positions_value': total_value - self.portfolio.cash
            })
        
        # Close all open positions at end date
        final_data = market_data[market_data['date'] == trading_dates[-1]]
        final_prices = dict(zip(final_data['symbol'], final_data['close']))
        self._close_all_positions(trading_dates[-1], final_prices)
        
        # Calculate final capital
        final_capital = self.portfolio.get_total_value(final_prices)
        
        # Calculate performance metrics
        metrics = self.calculate_metrics(
            self.portfolio.trades,
            pd.DataFrame(self.portfolio.equity_history)
        )
        
        # Create result
        result = BacktestResult(
            strategy_name="Strategy",
            start_date=start_date,
            end_date=end_date,
            initial_capital=self.config.initial_capital,
            final_capital=final_capital,
            metrics=metrics,
            equity_curve=pd.DataFrame(self.portfolio.equity_history),
            trades=self.portfolio.trades,
            positions=self.portfolio.positions,
            lookahead_violations=self.lookahead_violations
        )
        
        logger.info("backtest_simulation_completed",
                   total_trades=len(self.portfolio.trades),
                   final_capital=final_capital,
                   total_return=metrics.total_return,
                   lookahead_violations=len(self.lookahead_violations))
        
        return result
    
    def _execute_signal(
        self,
        signal: TradingSignal,
        current_prices: dict[str, float],
        current_date: datetime
    ):
        """Execute a trading signal."""
        symbol = signal.symbol
        
        # Get execution price
        if signal.price is not None:
            execution_price = signal.price
        elif symbol in current_prices:
            execution_price = current_prices[symbol]
        else:
            logger.warning("price_not_available",
                          symbol=symbol,
                          date=current_date.isoformat())
            return
        
        # Apply slippage
        if signal.signal_type == SignalType.BUY:
            execution_price *= (1 + self.config.slippage_rate)
        elif signal.signal_type == SignalType.SELL:
            execution_price *= (1 - self.config.slippage_rate)
        
        # Execute signal
        if signal.signal_type == SignalType.BUY:
            self._execute_buy(symbol, signal.quantity, execution_price, current_date)
        elif signal.signal_type == SignalType.SELL:
            self._execute_sell(symbol, signal.quantity, execution_price, current_date)
        elif signal.signal_type == SignalType.CLOSE:
            self._execute_close(symbol, execution_price, current_date)
    
    def _execute_buy(self, symbol: str, quantity: float, price: float, date: datetime):
        """Execute buy order."""
        # Calculate position size if quantity is 0 (use default)
        if quantity == 0:
            portfolio_value = self.portfolio.get_total_value({symbol: price})
            position_value = portfolio_value * self.config.position_size_pct
            quantity = position_value / price
        
        # Calculate costs
        cost = quantity * price
        commission = cost * self.config.commission_rate
        slippage = cost * self.config.slippage_rate
        total_cost = cost + commission + slippage
        
        # Check if we have enough cash
        if total_cost > self.portfolio.cash:
            logger.warning("insufficient_cash",
                          symbol=symbol,
                          required=total_cost,
                          available=self.portfolio.cash)
            return
        
        # Update cash
        self.portfolio.cash -= total_cost
        
        # Update or create position
        if symbol in self.portfolio.positions:
            # Add to existing position
            pos = self.portfolio.positions[symbol]
            total_quantity = pos.quantity + quantity
            pos.entry_price = (pos.entry_price * pos.quantity + price * quantity) / total_quantity
            pos.quantity = total_quantity
        else:
            # Create new position
            self.portfolio.positions[symbol] = Position(
                symbol=symbol,
                quantity=quantity,
                entry_price=price,
                entry_date=date
            )
        
        # Create trade record
        self.trade_counter += 1
        trade = Trade(
            trade_id=f"T{self.trade_counter:06d}",
            symbol=symbol,
            entry_date=date,
            entry_price=price,
            quantity=quantity,
            commission=commission,
            slippage=slippage
        )
        self.portfolio.trades.append(trade)
        
        logger.debug("buy_executed",
                    symbol=symbol,
                    quantity=quantity,
                    price=price,
                    total_cost=total_cost)
    
    def _execute_sell(self, symbol: str, quantity: float, price: float, date: datetime):
        """Execute sell order (close position)."""
        if symbol not in self.portfolio.positions:
            logger.warning("no_position_to_sell",
                          symbol=symbol)
            return
        
        pos = self.portfolio.positions[symbol]
        
        # Determine quantity to sell
        if quantity == 0 or quantity > pos.quantity:
            quantity = pos.quantity
        
        # Calculate proceeds
        proceeds = quantity * price
        commission = proceeds * self.config.commission_rate
        slippage = proceeds * self.config.slippage_rate
        net_proceeds = proceeds - commission - slippage
        
        # Update cash
        self.portfolio.cash += net_proceeds
        
        # Find corresponding open trade and close it
        for trade in reversed(self.portfolio.trades):
            if trade.symbol == symbol and trade.is_open():
                trade.close_trade(date, price, commission, slippage)
                break
        
        # Update or remove position
        pos.quantity -= quantity
        if pos.quantity <= 0:
            del self.portfolio.positions[symbol]
        
        logger.debug("sell_executed",
                    symbol=symbol,
                    quantity=quantity,
                    price=price,
                    net_proceeds=net_proceeds)
    
    def _execute_close(self, symbol: str, price: float, date: datetime):
        """Close entire position in symbol."""
        if symbol in self.portfolio.positions:
            self._execute_sell(symbol, 0, price, date)
    
    def _close_all_positions(self, date: datetime, prices: dict[str, float]):
        """Close all open positions at end of backtest."""
        symbols_to_close = list(self.portfolio.positions.keys())
        for symbol in symbols_to_close:
            if symbol in prices:
                self._execute_close(symbol, prices[symbol], date)
    
    def calculate_metrics(
        self,
        trades: list[Trade],
        equity_curve: pd.DataFrame
    ) -> PerformanceMetrics:
        """
        Calculate performance metrics from trades and equity curve.
        
        Args:
            trades: List of executed trades
            equity_curve: DataFrame with portfolio value over time
            
        Returns:
            PerformanceMetrics object
        """
        metrics = PerformanceMetrics()
        
        if len(trades) == 0 or len(equity_curve) == 0:
            logger.warning("no_trades_or_equity_data")
            return metrics
        
        # Filter closed trades
        closed_trades = [t for t in trades if not t.is_open()]
        
        if len(closed_trades) == 0:
            logger.warning("no_closed_trades")
            return metrics
        
        # Total trades
        metrics.total_trades = len(closed_trades)
        
        # Winning and losing trades
        winning_trades = [t for t in closed_trades if t.pnl > 0]
        losing_trades = [t for t in closed_trades if t.pnl < 0]
        
        metrics.winning_trades = len(winning_trades)
        metrics.losing_trades = len(losing_trades)
        
        # Win rate
        metrics.win_rate = metrics.winning_trades / metrics.total_trades if metrics.total_trades > 0 else 0.0
        
        # Average win/loss
        if winning_trades:
            metrics.average_win = sum(t.pnl for t in winning_trades) / len(winning_trades)
        if losing_trades:
            metrics.average_loss = abs(sum(t.pnl for t in losing_trades) / len(losing_trades))
        
        # Profit/loss ratio
        if metrics.average_loss > 0:
            metrics.profit_loss_ratio = metrics.average_win / metrics.average_loss
        
        # Calculate consecutive wins/losses
        consecutive_wins = 0
        consecutive_losses = 0
        max_consecutive_wins = 0
        max_consecutive_losses = 0
        
        for trade in closed_trades:
            if trade.pnl > 0:
                consecutive_wins += 1
                consecutive_losses = 0
                max_consecutive_wins = max(max_consecutive_wins, consecutive_wins)
            else:
                consecutive_losses += 1
                consecutive_wins = 0
                max_consecutive_losses = max(max_consecutive_losses, consecutive_losses)
        
        metrics.max_consecutive_wins = max_consecutive_wins
        metrics.max_consecutive_losses = max_consecutive_losses
        
        # Total return
        initial_value = equity_curve.iloc[0]['value']
        final_value = equity_curve.iloc[-1]['value']
        metrics.total_return = (final_value - initial_value) / initial_value
        
        # Annualized return
        days = (equity_curve.iloc[-1]['date'] - equity_curve.iloc[0]['date']).days
        years = days / 365.25
        if years > 0:
            metrics.annual_return = (1 + metrics.total_return) ** (1 / years) - 1
        
        # Maximum drawdown
        equity_curve = equity_curve.copy()
        equity_curve['cummax'] = equity_curve['value'].cummax()
        equity_curve['drawdown'] = (equity_curve['value'] - equity_curve['cummax']) / equity_curve['cummax']
        metrics.max_drawdown = abs(equity_curve['drawdown'].min())
        
        # Sharpe ratio
        equity_curve['returns'] = equity_curve['value'].pct_change()
        returns_mean = equity_curve['returns'].mean()
        returns_std = equity_curve['returns'].std()
        
        if returns_std > 0:
            # Annualize Sharpe ratio
            daily_rf_rate = (1 + self.config.risk_free_rate) ** (1/252) - 1
            excess_return = returns_mean - daily_rf_rate
            metrics.sharpe_ratio = (excess_return / returns_std) * np.sqrt(252)
        
        return metrics
    
    def generate_equity_curve(
        self,
        trades: list[Trade],
        initial_capital: float
    ) -> pd.DataFrame:
        """
        Generate equity curve from trades.
        
        Args:
            trades: List of trades
            initial_capital: Starting capital
            
        Returns:
            DataFrame with equity curve
        """
        if not trades:
            return pd.DataFrame(columns=['date', 'value'])
        
        # Create equity curve from trades
        equity_data = []
        current_equity = initial_capital
        
        for trade in sorted(trades, key=lambda t: t.entry_date):
            if trade.exit_date:
                current_equity += trade.pnl
                equity_data.append({
                    'date': trade.exit_date,
                    'value': current_equity
                })
        
        return pd.DataFrame(equity_data)
